version: "3"

services:

  mariadb:
    image: wodby/mariadb:latest
    container_name: "site_mariadb"
    stop_grace_period: 30s
    environment:
      MYSQL_ROOT_PASSWORD: site
      MYSQL_DATABASE: site
      MYSQL_USER: site
      MYSQL_PASSWORD: site
    ports:
      - "3306:3306"
    volumes:
      - mariadb:/var/lib/mysql
      - ./mariadb-init:/docker-entrypoint-initdb.d

  php:
    image: wodby/php:7.4
    container_name: "site_php"
    environment:
      PHP_XDEBUG: 1
      PHP_XDEBUG_IDEKEY: "PHPSTORM"
      PHP_XDEBUG_MODE: "debug"
      PHP_XDEBUG_CLIENT_HOST: 172.17.0.1
      PHP_XDEBUG_START_WITH_REQUEST: "yes"
      PHP_XDEBUG_DUMP_COOKIE: 1
      PHP_XDEBUG_DUMP_FILES: 1
      PHP_XDEBUG_DUMP_GET: 1
      PHP_XDEBUG_DUMP_POST: 1
      PHP_XDEBUG_DUMP_REQUEST: 1
      PHP_XDEBUG_DUMP_SERVER: 1
      PHP_XDEBUG_DUMP_SESSION: 1
      PHP_MAX_EXECUTION_TIME: 160
      PHP_POST_MAX_SIZE: "256M"
      PHP_UPLOAD_MAX_FILESIZE: "256M"
      PHP_MEMORY_LIMIT: "2408M"
      DB_HOST: localhost
      DB_USER: site
      DB_PASSWORD: site
      DB_NAME: site
    volumes:
      - ./public_html:/var/www/html

  nginx:
    image: wodby/nginx:latest
    container_name: "site_nginx"
    depends_on:
      - php
    environment:
      NGINX_VHOST_PRESET: wordpress
      NGINX_STATIC_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
    ports:
      - "80:80"
    volumes:
      - ./public_html:/var/www/html

volumes:
  mariadb:
    driver: local
